
services:
  db:
    image: postgres:16
    container_name: job_analytics_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always  
    ports:
      - 8080:8080

  cache:
    image: redis:latest
    container_name: job_analytics_cache
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: job_analytics_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - cache
    env_file:
      - .env

  celery:
    build: .
    container_name: job_analytics_celery
    command: celery -A job_analytics worker -l info
    volumes:
    - .:/app
    depends_on:
    - db
    - cache
    env_file:
    - .env
  celery-beat:
    build: .
    container_name: job_analytics_celery_beat
    command: celery -A job_analytics beat -l info
    volumes:
    - .:/app
    depends_on:
    - db
    - cache
    env_file:
    - .env



volumes:
  postgres_data: