services:
  db:
    image: postgres:16
    container_name: job_analytics_db
    restart: always
    environment:
      POSTGRES_DB=${DB_NAME}
      POSTGRES_USER=${DB_USER}
      POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    container_name: job_analytics_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: